name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: echo
      run: echo "start rust build"
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
